### ISSUE TITLE
set_resizable(false) does not make the window fully non-resizable on tiling window manager

### ISSUE THREAD

**Issue by someone-existing** [QuantumBadger/Speedy2D#11]
I'm running dwm - a tiling window manager. All windows are sorted in a grid, which means all windows(if resizable) get resized to fit the amount of screenspace left.
![2021-03-01-122940_1920x1080_scrot](https://user-images.githubusercontent.com/66226290/109491413-d35b0d00-7a89-11eb-9fb0-e5f68dd1cb15.png)
As you can see in the screenshot, the window gets resized to fit half of the screen even though I set the dimensions to be _640x480_ on **line 6**. Now, what if I don't want that and I'd like the window to keep it's intended size?
I messed around with the library a bit and found out I could do something like this:
```
impl WindowHandler for MyWindowHandler
{
    fn on_start(&mut self, helper: &mut WindowHelper, info: WindowStartupInfo) {
        helper.set_resizable(false);
    }
}
```
to make the window non-resizable.
And while doing that does make me unable to resize the window as a user, it still shows up like it did in the first screenshot. 
I'm guessing the `on_start` method gets called some time after the window actually gets created, so the system resizes the window before it turns non-resizabe.

**Comment by QuantumBadger** [comment]
Thanks for reporting this! I'll add an API to the window creation options, to allow the window to be set as non-resizable during creation.

**Comment by QuantumBadger** [comment]
I've added this to the latest master, will be in v1.1 when that gets released.

**Comment by QuantumBadger** [comment]
v1.1.0 is now released :) Thanks again for the report.
