### ISSUE TITLE
Different behavior on Windows and Linux 

### ISSUE THREAD

**Issue by arturocs** [QuantumBadger/Speedy2D#13]
When running this code on Linux, the circle moves down, but on Windows it doesn't. I am using speedy2d 1.0.5, the latest stable version of Rust and the gnu toolchain on Windows. 

```rust
use speedy2d::color::Color;
use speedy2d::window::{WindowHandler, WindowHelper};
use speedy2d::{Graphics2D, Window};

fn main() {
    let window = Window::new_centered("Title", (640, 480)).unwrap();
    window.run_loop(MyWindowHandler(0.0));
}

struct MyWindowHandler(f32);

impl WindowHandler for MyWindowHandler {
    fn on_draw(&mut self, helper: &mut WindowHelper, graphics: &mut Graphics2D) {
        graphics.clear_screen(Color::from_rgb(0.8, 0.9, 1.0));
        graphics.draw_circle((100.0, self.0), 75.0, Color::BLUE);
        self.0 += 1.0;
        helper.request_redraw();
    }
}
```

**Comment by QuantumBadger** [comment]
Thanks for reporting this!

This appears to be a bug in the winit library. I've added workarounds in https://github.com/QuantumBadger/Speedy2D/commit/851e96d8ba505f083fb71792941c1aeaeab5d6e5 and https://github.com/QuantumBadger/Speedy2D/commit/d0b881278aab3dbec68d6f199cdd79d89a3d61e0.

Version 1.0.6 is now published with those changes, please let me know if it resolves the issue for you!

**Comment by QuantumBadger** [comment]
Link to the relevant winit bug: https://github.com/rust-windowing/winit/issues/1619

**Comment by arturocs** [comment]
Yes, 1.0.6 fixes the issue.
