### ISSUE TITLE
shader program validation fails crashing the application

### ISSUE THREAD

**Issue by lzhelyaskov** [QuantumBadger/Speedy2D#14]
speedy2d ver. 1.0.6
windows 10

`use speedy2d::{Window};
use speedy2d::window::{WindowHandler};

fn main() {
    let window = Window::new_centered("Title", (640, 480)).unwrap();
    window.run_loop(MyWindowHandler{});
}
struct MyWindowHandler {}
impl WindowHandler for MyWindowHandler{}`

root cause glwrapper.rs, line:346 **"Program validate log was not empty: \'Validation warning! - Sampler value in_Texture has not been set.\nValidation successful.\n\'"**

`cause: Some(BacktraceError { error: ErrorMessage { description: "Failed to create Renderer2D program" }, backtrace:    0: backtrace::backtrace::trace     
   1: backtrace::capture::Backtrace::new
   2: speedy2d::error::BacktraceError<E>::new_with_cause
   3: <core::result::Result<R,E> as speedy2d::error::Context<R>>::context
   4: speedy2d::renderer2d::Renderer2D::new
   5: speedy2d::Window::new_with_options
   6: speedy2d::Window::new_centered
   7: <winit::dpi::PhysicalSize<P> as core::fmt::Debug>::fmt
   8: std::sys_common::backtrace::__rust_begin_short_backtrace
   9: <std::sync::mpsc::stream::Packet<T> as core::ops::drop::Drop>::drop
  10: core::ops::function::impls::{{impl}}::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\library\core\src\ops\function.rs:280
  11: std::panicking::try::do_call
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\panicking.rs:379
  12: std::panicking::try
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\panicking.rs:343
  13: std::panic::catch_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\panic.rs:396
  14: std::rt::lang_start_internal
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\rt.rs:51
  15: main
  16: invoke_main
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  17: __scrt_common_main_seh
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  18: BaseThreadInitThunk
  19: RtlUserThreadStart
, cause: Some(BacktraceError { error: GLError { description: "Program validate log was not empty: \'Validation warning! - Sampler value in_Texture has not been set.\nValidation successful.\n\'" }, backtrace:    0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: speedy2d::glwrapper::GLContextManager::new_program
   3: speedy2d::renderer2d::Renderer2D::new
   4: speedy2d::Window::new_with_options
   5: speedy2d::Window::new_centered
   6: <winit::dpi::PhysicalSize<P> as core::fmt::Debug>::fmt
   7: std::sys_common::backtrace::__rust_begin_short_backtrace
   8: <std::sync::mpsc::stream::Packet<T> as core::ops::drop::Drop>::drop
   9: core::ops::function::impls::{{impl}}::call_once
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\library\core\src\ops\function.rs:280
  10: std::panicking::try::do_call
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\panicking.rs:379
  11: std::panicking::try
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\panicking.rs:343
  12: std::panic::catch_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\panic.rs:396
  13: std::rt::lang_start_internal
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b\/library\std\src\rt.rs:51
  14: main
  15: invoke_main
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  16: __scrt_common_main_seh
             at d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  17: BaseThreadInitThunk
  18: RtlUserThreadStart
, cause: None }) }) }) }', src\main.rs:6:60`

**Comment by QuantumBadger** [comment]
Thanks for reporting this. We shouldn't actually be running validation there as the buffers/texture/etc haven't been set up.

I've fixed this in v1.0.7, which is published now. Please let me know if you see any other issues!
