### ISSUE TITLE
Add support for clipping

### ISSUE THREAD

**Issue by Revertron** [QuantumBadger/Speedy2D#17]
Speedy2D is like a Canvas, and every canvas needs some sort of `set_clip()` or `clip_rect()` functions to set a stencil area. Ideally with a stack to pop current clip and go back to previous one. (Or just a getter for current clip state as last resort).

For example, user can have a big atlas-map with sprites and want to draw that map over a clip-rect to paint only a small "window" of it.

**Comment by QuantumBadger** [comment]
Thanks for the suggestion, this is something I'm happy to add (or would accept a PR for). I suspect we'd want to use `glScissor()` internally to do this:

https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glScissor.xhtml

> For example, user can have a big atlas-map with sprites and want to draw that map over a clip-rect to paint only a small "window" of it.

This is actually already possible using [`draw_rectangle_image_subset_tinted()`](https://docs.rs/speedy2d/1.0.7/speedy2d/struct.Graphics2D.html#method.draw_rectangle_image_subset_tinted) -- the `image_coords_normalized` parameter can be used to specify which portion of the source image should be drawn (i.e. the location of the sprite in the atlas), and anything outside those bounds is cropped.

**Comment by Revertron** [comment]
> This is actually already possible...

Ah, I've forgotten that part of docs! Of course! :)
