### ISSUE TITLE
Approach to Image Processing? 

### ISSUE THREAD

**Issue by wyhinton** [QuantumBadger/Speedy2D#22]
Hello,

I'm curious as to the thinking behind  speedy2d tinting functions, i.e. ```draw_quad_image_tinted_four_color()```, ```draw_rectangle_subset_tinted()```, etc. Why facilitate tinting as opposed to some of the other color operations, like hue, saturation, or contrast? In the future do you think speedy2d will have more functions like ```draw_rectangle_subset_contrast()```, or ```draw_rectangle_subset_inverted()```?

**Comment by QuantumBadger** [comment]
Thanks for the question! The tinting functions multiply each component of the image color with the specified color, so for example if the image is white `(1, 1, 1)`, and you tint it with red `(1, 0, 0)`, the output will be red `(1, 0, 0)`.

This was originally added for rendering text. The character textures are white text on a transparent background, which allows text to be drawn in any color using the "tinting" method above.

Adding other color operations such as contrast/inverting/etc would make the fragment shader more complex and hence reduce performance (even if someone didn't use that feature), so unfortunately there are no plans to do this. With the current API you'd have to make adjustments to the image before providing it to the library.
