### ISSUE TITLE
Compilation error - crossbeam-epoch-0.9.3

### ISSUE THREAD

**Issue by LovaTahina** [QuantumBadger/Speedy2D#24]
Hi,

I get 2 compile errors with crossbeam-epoch-0.9.3
    |
620 |         let local_ptr = (entry as *const Entry as usize - offset_of!(Local, entry)) as *const Local;
    |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^ could not find `addr_of` in `ptr`
613 |         let entry_ptr = (local as *const Local as usize + offset_of!(Local, entry)) as *const Entry;
    |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^ could not find `addr_of` in `ptr`

What can I do?

**Comment by QuantumBadger** [comment]
Thanks for the report! Which version of the rust compiler are you using? It's probably a good idea to run `rustup update` to make sure you have the latest toolchain.

**Comment by LovaTahina** [comment]
Thanks for your help, it compiles now

**Comment by QuantumBadger** [comment]
Glad to hear it :) If you have any more questions just let me know.
