### ISSUE TITLE
Roadmap/Project Status?

### ISSUE THREAD

**Issue by wyhinton** [QuantumBadger/Speedy2D#26]
Hey, just wanted to say thanks again for all your wonderful work on this project.

I see that it's been a couple months since the last update, is further development on the project planned in the foreseeable future?

**Comment by QuantumBadger** [comment]
Thanks for the question! I work on this project in my free time, which unfortunately has been limited over the last few weeks.

In terms of my plans for the project in the near future, I'm hoping to have WebGL and GL ES supported added and tested soon, and then will move on to adding more features, e.g. render-to-texture.

**Comment by wyhinton** [comment]
Understood! Thanks for the update.
