### ISSUE TITLE
Support for mouse scroll wheel events

### ISSUE THREAD

**Issue by QuantumBadger** [QuantumBadger/Speedy2D#28]
We should send an event to the `WindowHandler` when the user scrolls using the mouse wheel.

**Comment by blaumeise20** [comment]
Please add this! I really need it.

**Comment by QuantumBadger** [comment]
I'm hoping to add this within the next couple of weeks.

**Comment by GreatGodOfFire** [comment]
Hello, I implemented it and opened pull request #51.

**Comment by QuantumBadger** [comment]
v1.4.0 now published :) Thanks @GreatGodOfFire!
