### ISSUE TITLE
Wayland Support

### ISSUE THREAD

**Issue by RiedleroD** [QuantumBadger/Speedy2D#31]
On wayland (specifically sway in my case), speedy2D 1.1.0 immediately errorrs out when a new window is created.

backtrace: [traceback.txt](https://github.com/QuantumBadger/Speedy2D/files/6951388/traceback.txt)
main.rs (github doesn't support attaching .rs files so I had to edit the file extension): [main.txt](https://github.com/QuantumBadger/Speedy2D/files/6951389/main.txt)

Wayland support would be nice to have.

**Comment by QuantumBadger** [comment]
Thanks for reporting this! Looks like there's an issue getting the primary monitor on Wayland. Should be easy enough to work around, but we might not be able to initially position/size the window.

**Comment by QuantumBadger** [comment]
This should now be fixed in v1.1.1, I've tested this in Weston. Thanks again for the report!

**Comment by RiedleroD** [comment]
can confirm, wayland now works without issues in v1.1.1 - great work!
