### ISSUE TITLE
Multithreading and UserEventSender

### ISSUE THREAD

**Issue by f-fuchs** [QuantumBadger/Speedy2D#38]
Hey,

as I understand you can use the UserEventSender class to send events from other threads, but I do not understand how to actually do it.
I tried the following:
```
    fn on_start(&mut self, helper: &mut WindowHelper<String>, info: WindowStartupInfo) {
        log::info!("Got on_start callback: {:?}", info);
        helper.set_cursor_visible(false);
        helper.set_resizable(false);

        thread::spawn(|| {
            loop {
                // Request that we draw another frame once this one has finished
                self.redraw_event_sender.send_event("redraw".to_string());
                thread::sleep(Duration::from_millis(15));
            }
        });
    }
```
But I get following error:
`*mut winapi::shared::windef::HWND__` cannot be shared between threads safely
within `UserEventSender<String>`, the trait `Sync` is not implemented for `*mut winapi::shared::windef::HWND__`
required because of the requirements on the impl of `Send` for `&UserEventSender<String>`
required because it appears within the type `[closure@src\main.rs:80:23: 86:10]`rustcE0277
main.rs(1, 1): required because it appears within the type `winit::platform_impl::platform::event_loop::EventLoopProxy<String>`
main.rs(1, 1): required because it appears within the type `winit::event_loop::EventLoopProxy<String>`
main.rs(1, 1): required because it appears within the type `UserEventSender<String>`
mod.rs(627, 8): required by a bound in `spawn`
`Sender<String>` cannot be shared between threads safely
within `UserEventSender<String>`, the trait `Sync` is not implemented for `Sender<String>`
required because of the requirements on the impl of `Send` for `&UserEventSender<String>`
required because it appears within the type `[closure@src\main.rs:80:23: 86:10]`rustcE0277
main.rs(1, 1): required because it appears within the type `winit::platform_impl::platform::event_loop::EventLoopProxy<String>`
main.rs(1, 1): required because it appears within the type `winit::event_loop::EventLoopProxy<String>`
main.rs(1, 1): required because it appears within the type `UserEventSender<String>`
mod.rs(627, 8): required by a bound in `spawn`

I also tried to use the move keyword, but then I get an other error:
`self` has an anonymous lifetime `'_` but it needs to satisfy a `'static` lifetime requirement
...is captured here...rustcE0759
main.rs(75, 17): this data with an anonymous lifetime `'_`...
main.rs(80, 9): ...and is required to live as long as `'static` here.

But I can´t change self to static because then the method signature would be wrong.
Therefore I wanted to ask how you send events from other threads and maybe where it is ideally to spawn the thread.

**Comment by QuantumBadger** [comment]
Thanks for raising this. The errors make sense -- you need to make a clone of the `UserEventSender` and then move it into the thread:

```rust
let user_event_sender = self.user_event_sender.clone();

std::thread::spawn(move || {
    user_event_sender.send_event("Message from thread".to_string()).unwrap();
});
```

However when testing this I've come across another problem relating to the use of `Arc` internally -- I'll put in a fix for this later today. I'll also update the user events sample to make it clear how to use it.

**Comment by f-fuchs** [comment]
Thanks for the quick response. The cloning fixed my error.

**Comment by QuantumBadger** [comment]
Perfect, thanks for the update :) Looks like the Arc issue only exists in the WebGL branch, so the release version should work fine.
