### ISSUE TITLE
Add an method to continue the event loop without redraw

### ISSUE THREAD

**Issue by d0rianb** [QuantumBadger/Speedy2D#43]
I have the following code in my `on_draw` method : 
```rust
 fn on_draw(&mut self, helper: &mut WindowHelper, graphics: &mut Graphics2D) {
        if !self.is_dirty { return; }
        graphics.clear_screen(Color::WHITE);
        self.editor.render(graphics);
        self.is_dirty = false;
        helper.request_redraw();
    }
```
But it seems that the return line 2 stop the event loop and the `on_draw` is never called after.
I have not found any solution for toggling the ControlFlow::Wait or to simply ignore the draw call during a loop iteration.

**Comment by QuantumBadger** [comment]
Thanks for the report!

The event loop should continue running even if you return on line 2, and you should continue to receive mouse/keyboard/etc events.

However, the `on_draw()` callback is only called when necessary -- this is either (1) when the window is created/resized, or (2) when `request_redraw()` is called. Unless one of these is true, `on_draw()` will not be called.

So you need to call `request_redraw()` from other callbacks (e.g. mouse/keyboard) whenever you set `self.is_dirty` to true. (Also the call to `helper.request_redraw()` in the code above can be removed as it will cause `on_draw()` to be called unnecessarily)

**Comment by d0rianb** [comment]
Thanks for your answer. It works !
