### ISSUE TITLE
Text rendering drawing square instead of glyph

### ISSUE THREAD

**Issue by d0rianb** [QuantumBadger/Speedy2D#55]
When I use `graphics.draw_text(...)`, I often get black rectangle instead of the text at the first frame : 
<img width="183" alt="screenshot" src="https://user-images.githubusercontent.com/36789001/151523250-77c58429-d549-47b0-ab0d-9acf28f534c9.png"><img width="165" alt="screenshot" src="https://user-images.githubusercontent.com/36789001/151523336-47e0bae8-b15d-4cbc-a3de-0ede2f33a8d1.png">
When I ask for a redraw, (and so I update the text layout), the next frame is clean and the text appears clear.
Is it an issue with `Rc<FormattedTextBlock>` ?

**Comment by QuantumBadger** [comment]
Would you be able to take an OpenGL trace of this issue occurring and send it to me please? This can be done using the apitrace tool:

```
apitrace trace <your program>
```

**Comment by d0rianb** [comment]
Unfortunatly I can't figure out how to get `apitrace` working on macOs. I still have errors with 'OpenGl Framework not found' since it has been deprecated a few time ago by Apple :(

**Comment by QuantumBadger** [comment]
I've finally managed to reproduce this issue! It seems to occur if there are frames where no text is drawn, followed by frames where text does get drawn. I need to investigate this more.

**Comment by QuantumBadger** [comment]
Now released in v1.10.0!
