### ISSUE TITLE
Support for += for Vector2

### ISSUE THREAD

**Issue by amarao** [QuantumBadger/Speedy2D#65]
I've tried to write `foo += bar`, where both `foo` and `bar` are Vector2<f32>, and found that I can't:

```
binary assignment operation `+=` cannot be applied to type `Vector2<f32>`
```

But I can write `foo = foo + bar`, so it's not a political decision, I think.

**Comment by QuantumBadger** [comment]
Yep it would definitely good to have this, as you say it's not a political decision :)

**Comment by QuantumBadger** [comment]
This has been merged in, thanks again @amarao!
