### ISSUE TITLE
Is it possible to save the current frame into a file?

### ISSUE THREAD

**Issue by seahawk1986** [QuantumBadger/Speedy2D#67]
Hello,
I saw that accessing the framebuffer fo taking screenshots seems to be possible in https://github.com/QuantumBadger/Speedy2D/blob/master/test/main.rs#L64 ff. - is there a way to do this when Speedy2D is managing the window?

**Comment by QuantumBadger** [comment]
Thanks for raising this, I've added this feature here: https://github.com/QuantumBadger/Speedy2D/commit/31c06164caf447d50f8ec3d056c0d9415c74f145

Let me know if it works for you, if so I'll release it as part of v1.9.0 :)

**Comment by seahawk1986** [comment]
Thank you very much for the fast reply. I tried it on a machine with Windows 10 and was able to save a screenshot using the `image` crate at the end of my `on_draw` method:
````rust
use image::{ImageBuffer, ImageFormat, Rgba};
// [...]
    fn on_draw(&mut self, _helper: &mut WindowHelper, graphics: &mut Graphics2D) {
        // draw some stuff...
        if self.screenshot_wanted {
            let raw = graphics.capture(ImageDataType::RGBA);
            let image: ImageBuffer<Rgba<u8>, _> =
                ImageBuffer::from_raw(raw.size().x, raw.size().y, raw.data().as_slice()).unwrap();

            image
                .save_with_format("screenshot.png", ImageFormat::Png)
                .unwrap();

            self.screenshot_wanted = false;
        }
    }
````
