### ISSUE TITLE
Use different GL bindings to support WebGL/GLES

### ISSUE THREAD

**Issue by QuantumBadger** [QuantumBadger/Speedy2D#7]
Instead of using `gl` for OpenGL bindings, we could switch to something like `wgpu-rs` or `glow`, which should improve cross-platform support.

**Comment by QuantumBadger** [comment]
I've started work on moving to `glow`. Not as easy as I first thought, because:

1. We now need to pass a context object around everywhere
2. To maintain backwards compatibility with the `GLRenderer::new_for_current_context()` API, we'll still need to support the `gl` bindings, and decide which bindings to use at runtime

Making progress though!

**Comment by morr0ne** [comment]
Wgpu is a completely different api. It's inspired by Vulkan but is completely cross-platform. It uses the native API of the platform: DirectX on windows, metal on ios/macOS, Vulkan/OpenGL for Linux/android, and WebGL or native wpgu implementation of browser.
It's harder to use but guarantee that the library is as portable as possible so it may be worth switching to that

**Comment by QuantumBadger** [comment]
Thank you for the info @morr0ne, it does sound like it would be worth making use of `wgpu-rs` in future, while maintaining support for OpenGL 2.0 using the existing backend.

Since `glow` is a much smaller (and mostly unrelated) change, I'll finish that for now, and then raise a separate issue for `wgpu-rs`.

**Comment by QuantumBadger** [comment]
Support for glow is now pushed. I've added a new API `GLRenderer::new_for_gl_context()` which takes a loader function, and deprecates the old `new_for_current_context` API which relied on the `gl` bindings.

To actually make WebGL/GLES work I think there will need to be some minor shader changes. I'll create some sample code for the WebGL target to test it and see what needs changing.

**Comment by QuantumBadger** [comment]
Initial WebGL implementation for `GLRenderer` now working locally (see image below :)). The API is nice and simple, you can just call `GLRenderer::new_for_web_canvas_by_id()` with the id of the canvas.

I'm going to try and make it possible to use an existing `WindowHandler` with a canvas as well. I.e. Speedy2D will automatically hook in all the mouse/keyboard events, given the id of the canvas.

![Screenshot from 2021-07-11 16-40-43](https://user-images.githubusercontent.com/2998158/125201384-cd124400-e266-11eb-89c8-891184ea6cad.png)

**Comment by QuantumBadger** [comment]
Lots of `WindowHandler` features working now, including mouse and keyboard input. Still some work left to do to tidy up the remaining features.

![Screenshot from 2021-11-26 14-26-44](https://user-images.githubusercontent.com/2998158/143595554-dcca635b-24f2-4671-85de-90f69f064335.png)

**Comment by QuantumBadger** [comment]
Before merging into master I'll be doing some testing of this in various browsers. If anyone wants to give it a go in their own browser, I've uploaded a demo here:

https://redreader.org/s2dweb/

* Keyboard events should appear in the web console
* Mouse events should be handled (and allow you to click the buttons)
* If you zoom in/out (or have a high DPI monitor), the scale of the interface should change and remain high resolution

**Comment by QuantumBadger** [comment]
This is now merged into master, so I'm resolving the ticket. I've spun out #42 to cover GLES support on Android/iOS.

**Comment by Revertron** [comment]
Works perfectly in current Firefox.
