### ISSUE TITLE
Can't get glyph coords and sizes

### ISSUE THREAD

**Issue by Revertron** [QuantumBadger/Speedy2D#72]
I'm trying to continue my work on GUI library.
And as I work on `Edit` component I desperately need glyph positions and sizes of `FormattedTextBlock`.
For example, as I need to draw text cursor between glyphs, I need to know where this cursor should be in pixels.

Can we add some method to get this info from `FormattedGlyph`?

**Comment by QuantumBadger** [comment]
In version 1.9.0 I added some methods to `FormattedGlyph` (`position_x`, `advance_width`, etc) which should let you do this! See also the additions to `FormattedTextLine` which give you information about the y coordinates of each line.

**Comment by Revertron** [comment]
BTW, I've tested it, and current methods are sufficient for my needs. Thanks! :)
