### ISSUE TITLE
What is the best way to draw one pixel?

### ISSUE THREAD

**Issue by Revertron** [QuantumBadger/Speedy2D#73]
I need to draw some sophisticated figure like pixel art. How can I plot one pixel of some color?
`draw_line()` doesn't give clear colored pixel.

**Comment by QuantumBadger** [comment]
Hey! It would be possible to use `draw_rectangle` for this, however this will be quite slow if you're plotting more than a few thousand pixels per frame.

A quicker way is to draw the pixels to an image, and then use `draw_image()` to draw them all at once. `create_image_from_raw_pixels()` takes an array of color values (RGB or RGBA) representing the image, and you'd have to call this once per frame (which is a bit expensive performance-wise, but faster than drawing thousands of rectangles).
