### ISSUE TITLE
Consider exposing window size from Graphics2D

### ISSUE THREAD

**Issue by matklad** [QuantumBadger/Speedy2D#76]
When drawing onto a resizable window, it's useful to know the current window size. Right now, I get it by storing the current size in my Handler and updating it on `on_draw`, but it would perhaps be more natural to have something like

```rust
impl Graphics2D {
    fn size(&self) -> Vec2;
}
```

Just so that one doesn't need to think about converting between integral pixels and float coordinates graphics is using for most stuff.

**Comment by dennisorlando** [comment]
Would #78 be a solution? It's not attached directly to Graphics2D but to the WindowHelper that gets passed with the draw() methods

**Comment by matklad** [comment]
Yup!

**Comment by QuantumBadger** [comment]
Now merged, thank you @dennisorlando!
