### ISSUE TITLE
How can I do an Image programmatically?

### ISSUE THREAD

**Issue by raffaelemazziotti** [QuantumBadger/Speedy2D#77]
Hey, really nice work, really easy to use and useful!
I have a request!
I'm a noob in Rust. 
I'm trying to understand how to create a custom image programmatically.
I have understood that I need to use [create_image_from_raw_pixels](https://docs.rs/speedy2d/latest/speedy2d/struct.Graphics2D.html#method.create_image_from_raw_pixels). However I can't figure out how I can edit pixels, and use images in the code. There seem to be no examples of how to use images. Could you please help me or add one or more examples of how to manipulate images? Thanks in advance

**Comment by QuantumBadger** [comment]
Thanks for the question! To make an image programatically, you need a list of pixel colour values. Each pixel is made up of either three (RGB) or four (RGBA) bytes.

```rust
let mut col = Vec::<u8>::new();

// First pixel
col.push(0x00); // Red
col.push(0xFF); // Green
col.push(0xFF); // Blue

// Second pixel
col.push(0xFF); // Red
col.push(0x00); // Green
col.push(0xFF); // Blue
```

The code above creates a vector with two RGB pixels: the first one is cyan (`#00FFFF`) and the second one is magenta (`#FF00FF`);

In a 1920x1080 image, you would need `1920 * 1080 = 2073600` pixels. All the rows of the pixels are "flattened" into a straight line in the vector: the first 1920 pixels in the vector are the first row, the next 1920 are the second row, etc.

To turn that vector into a Speedy2D image, you can use `create_image_from_raw_pixels()`:

```rust
let image = graphics.create_image_from_raw_pixels(
      ImageDataType::RGB,
      ImageSmoothingMode::NearestNeighbor,
      (1, 2), // Size of the image: 1 pixel wide and 2 pixels high
      col.as_slice()
).unwrap();
```

Which can then be drawn as follows:

```rust
graphics.draw_image((50.0, 50.0), &image);
```

Hopefully that makes sense! Let me know if you have any more questions. I'll leave this ticket open to improve the documentation for this.

**Comment by QuantumBadger** [comment]
One other thing since you mentioned editing images: To change part of the image, modify the original vector, and then call `create_image_from_raw_pixels()` again to create a new image from that vector.

**Comment by raffaelemazziotti** [comment]
Thanks for the quick help.
I managed to resolve this by myself after struggling all day. In the end, I arrived at a nice solution (very similar to that you posted) and I'm really happy about that. I started using Rust yesterday so certain things look really strange to me. 
However, your comment is really helpful because I was not sure if my code implementation was decent.
