### ISSUE TITLE
Raspberry Pi performance

### ISSUE THREAD

**Issue by superlou** [QuantumBadger/Speedy2D#83]
This my own limited misunderstanding, but on a Raspberry Pi 3, does the follow glxinfo output meet what Speedy2D needs? I think this is OpenGL and not OpenGLES, but maybe that explains why I have slow performance:

```
OpenGL vendor string: Broadcom
OpenGL renderer string: VC4 V3D 2.1
OpenGL version string: 2.1 Mesa 20.3.5
OpenGL shading language version string: 1.20
```

Running at low resolutions (640x480) is very performant (60 FPS), but as I expand the window frame, it slows down dramatically. Is there a way to scale more cheaply than expand the resolution?

**Comment by QuantumBadger** [comment]
Thanks for reporting this! Could you give me a full log please?

Also, which functions are you calling in your `on_draw()` callback? You should call `clear_screen()` at the start of every frame for best performance, particularly on embedded GPUs.

**Comment by superlou** [comment]
Is there a logging function I should enable in the API? I can try to run that and get a log tonight.

In `on_draw(...)`, I'm calling `clear_screen`, `DrawRectangle`, `DrawText`, `DrawImage`, and `DrawRectangleImageTinted` (https://github.com/superlou/signrs/blob/main/src/window_handler.rs#L45). The first thing done is clear_screen (I apologize that this is in a script rather than Rust with the Speedy2D API, though the script calls are a very thin layer over Speedy2D):

https://github.com/superlou/signrs/blob/be259915b630551e4b9e5273c2b38f40a9af4141/examples/display1/main.rhai#L15-L38

I don't think it's the scripting layer causing the performance issue since it runs at 60 FPS when the window is small, and it's only slow when the window frame is enlarged.

**Comment by superlou** [comment]
I tried disabling the compositor, and now when I expand the 640x480 window to full screen, it only goes down to 22 FPS rather than 8 or 9, which is a big improvement. That said, the expanded window isn't drawing a lot:

![image](https://user-images.githubusercontent.com/709695/231611870-a6575517-607c-4df8-8019-552d4cd85ac9.png)

**Comment by QuantumBadger** [comment]
Awesome, glad to hear it's running at 60fps now! Regarding scaling -- all of Speedy2D's drawing operations use physical pixels, for maximum control and performance, so there's no built in "scale" function. To scale everything up it's necessary to multiply the sizes/coordinates of the things you're drawing.

**Comment by superlou** [comment]
Ah, I wasn't sure if `WindowSize::ScaledPixels` (https://docs.rs/speedy2d/latest/speedy2d/window/enum.WindowSize.html) was more about scaling the viewport or maybe its for HiDPI scaling?

It might be more of a "game UI" vs. "application UI," thing, but I wonder if there's a cheap OpenGL viewport way to have some set resolution, but stretch everything to fit. It makes sense to multiply the sizes/coordinates of everything for most objects, but the scale for text doesn't seem to have a way to scale x and y independently. I've seen other OpenGL backend applications just stretch things (Godot, info-beamer) with objects like text and images getting blurrier, so I'll have to do some digging. Either way, probably a separate issue.
