### ISSUE TITLE
No support for ascii input (è, +, } etc...)

### ISSUE THREAD

**Issue by dennisorlando** [QuantumBadger/Speedy2D#85]
Hi,
I'm trying to get a simple text editor working but it appears to be very challenging given that VirtualKeyCode doesn't include all the characters and that the "KeyScancode to Ascii code" problem appears to be a problem which there are no libraries for (I literally can't find anything on the internet other than open issues and hardcoded maps).
It appears that this issue also propagates to winit and glutin; is there any way to solve this? 

Possible things that might be worth looking into:
- Linux layout kernel stuff (I'm on Linux) (I've read that the scancode->key conversion might be done in the kernel)
- external libraries that can already handle keys? Maybe some folks like egui or some other text editors already solved this problem

**Comment by dennisorlando** [comment]
there's the "lapce" text editor written in rust that appears to be using the "druid" library

**Comment by superlou** [comment]
> there's the "lapce" text editor written in rust that appears to be using the "druid" library

I think lapce is [migrating](https://github.com/lapce/lapce/tree/floem) to a custom framework called Floem, which is based on the [Xilem architecture](https://raphlinus.github.io/rust/gui/2022/05/07/ui-architecture.html).

**Comment by QuantumBadger** [comment]
I think the callback you're looking for is `on_keyboard_char` -- this gives you the Unicode codepoint of which key was pressed, for the purpose of text entry.

`on_key_up` and `on_key_down` are aimed at things like games, where you want to know when a specific keyboard key was pressed/released, so these shouldn't be used for text entry.

**Comment by dennisorlando** [comment]
> I think the callback you're looking for is `on_keyboard_char` -- this gives you the Unicode codepoint of which key was pressed, for the purpose of text entry.
> 
> `on_key_up` and `on_key_down` are aimed at things like games, where you want to know when a specific keyboard key was pressed/released, so these shouldn't be used for text entry.

oh, there it is! Works like a charm, thanks
