### ISSUE TITLE
Cheaply scaling drawing

### ISSUE THREAD

**Issue by superlou** [QuantumBadger/Speedy2D#86]
I understand that the intent of this library is to do all drawing in physical pixels, so the user can handle application-specific logic (e.g. snapping to integer pixel positions for crisp lines) if needed. I think that paradigm makes the most sense for making "applications," e.g., a text editor with GUI controls and menus. I'm trying to use Speedy2D for something more like a game application, where in order to run fast enough, I'm willing to render at lower resolutions and let OpenGL scale it up cheaply, accepting the loss of quality and control.

Is it possible to use something like the OpenGL projection matrix for this without managing the custom GL context? Is there another approach that could be used?

(Following up on a bit of conversation from https://github.com/QuantumBadger/Speedy2D/issues/83)

**Comment by dennisorlando** [comment]
maybe #75 might help? My clue is that you render to the context and then you manually upscale it to a window with some other libraries

**Comment by superlou** [comment]
I think that would work for upscaling, but if I ever want to downscale (e.g. in my app: design a display for 1920x1080 but scale the window smaller so it's easy to test on a monitor). I'm a little convinced I can mess with the uniforms (https://github.com/QuantumBadger/Speedy2D/blob/master/src/renderer2d.rs#L178) that are setting scale_x and scale_y or the viewport, but I have to learn how OpenGL's works.

**Comment by superlou** [comment]
I'm going to close this in favor of a new issue based on the discussion from #88.
