### ISSUE TITLE
Text outline

### ISSUE THREAD

**Issue by mazsibazsi** [QuantumBadger/Speedy2D#87]
Hello!

I am looking to add outlines to my text. 

I have a bunch of kfn (karaoke) files, made by volunteers, and I am building a player for those files. Hence fonts, text colors and text outline colors are already given, and I would like to respect those choices as much as possible. 

Is there any way I could outline individual characters, so that it remains readable, unlike picrel?
![kép](https://user-images.githubusercontent.com/32135909/233001746-5fe68d03-90a8-4bd1-8f5c-e8d39dbae394.png)

**Comment by Revertron** [comment]
You can draw the same text in outline color 1-2 pixels up, down, right and left, and then draw the actual text over it.

**Comment by Revertron** [comment]
That's how we were doing it in the era of J2ME phones ;)
